/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExtractionRouteImport } from './routes/extraction'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as CallsIndexRouteImport } from './routes/calls.index'
import { Route as CallsCallIdRouteImport } from './routes/calls.$callId'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates.$candidateId'
import { Route as ApiAnalyticsIndexRouteImport } from './routes/api/analytics/index'
import { Route as ApiAnalyticsCallsRouteImport } from './routes/api/analytics/calls'
import { Route as ApiAnalyticsCandidatesRouteImport } from './routes/api/analytics/candidates'
import { Route as ApiCallsInitiateRouteImport } from './routes/api/calls/initiate'
import { Route as ApiCallsWebhookRouteImport } from './routes/api/calls/webhook'
import { Route as ApiCandidatesIndexRouteImport } from './routes/api/candidates/index'
import { Route as ApiCandidatesIdRouteImport } from './routes/api/candidates/$id'
import { Route as ApiCandidatesUploadRouteImport } from './routes/api/candidates/upload'
import { Route as ApiCronRetentionRouteImport } from './routes/api/cron/retention'
import { Route as ApiInterviewsIndexRouteImport } from './routes/api/interviews/index'
import { Route as ApiInterviewsIdRouteImport } from './routes/api/interviews/$id'
import { Route as ApiInterviewsAvailabilityRouteImport } from './routes/api/interviews/availability'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiJobsSyncRouteImport } from './routes/api/jobs/sync'
import { Route as ApiPublicElevenlabsCallRouteImport } from './routes/api/public/elevenlabs-call'
import { Route as ApiReportsTranscriptsRouteImport } from './routes/api/reports/transcripts'
import { Route as ApiCallsIdRecordingRouteImport } from './routes/api/calls/$id/recording'
import { Route as ApiCallsIdStatusRouteImport } from './routes/api/calls/$id/status'
import { Route as ApiCallsIdTranscriptRouteImport } from './routes/api/calls/$id/transcript'
import { Route as ApiCandidatesIdExportRouteImport } from './routes/api/candidates/$id/export'
import { Route as ApiIntegrationsMicrosoftAuthorizeRouteImport } from './routes/api/integrations/microsoft/authorize'
import { Route as ApiIntegrationsMicrosoftCallbackRouteImport } from './routes/api/integrations/microsoft/callback'
import { Route as ApiIntegrationsZohoAuthorizeRouteImport } from './routes/api/integrations/zoho/authorize'
import { Route as ApiIntegrationsZohoCallbackRouteImport } from './routes/api/integrations/zoho/callback'
import { Route as ApiPublicCallsWebhookRouteImport } from './routes/api/public/calls/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionRoute = ExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsCallIdRoute = CallsCallIdRouteImport.update({
  id: '/calls/$callId',
  path: '/calls/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/candidates/$candidateId',
  path: '/candidates/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsIndexRoute = ApiAnalyticsIndexRouteImport.update({
  id: '/api/analytics/',
  path: '/api/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsCallsRoute = ApiAnalyticsCallsRouteImport.update({
  id: '/api/analytics/calls',
  path: '/api/analytics/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsCandidatesRoute = ApiAnalyticsCandidatesRouteImport.update({
  id: '/api/analytics/candidates',
  path: '/api/analytics/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsInitiateRoute = ApiCallsInitiateRouteImport.update({
  id: '/api/calls/initiate',
  path: '/api/calls/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsWebhookRoute = ApiCallsWebhookRouteImport.update({
  id: '/api/calls/webhook',
  path: '/api/calls/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidatesIndexRoute = ApiCandidatesIndexRouteImport.update({
  id: '/api/candidates/',
  path: '/api/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidatesIdRoute = ApiCandidatesIdRouteImport.update({
  id: '/api/candidates/$id',
  path: '/api/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidatesUploadRoute = ApiCandidatesUploadRouteImport.update({
  id: '/api/candidates/upload',
  path: '/api/candidates/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRetentionRoute = ApiCronRetentionRouteImport.update({
  id: '/api/cron/retention',
  path: '/api/cron/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewsIndexRoute = ApiInterviewsIndexRouteImport.update({
  id: '/api/interviews/',
  path: '/api/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewsIdRoute = ApiInterviewsIdRouteImport.update({
  id: '/api/interviews/$id',
  path: '/api/interviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewsAvailabilityRoute =
  ApiInterviewsAvailabilityRouteImport.update({
    id: '/api/interviews/availability',
    path: '/api/interviews/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsSyncRoute = ApiJobsSyncRouteImport.update({
  id: '/api/jobs/sync',
  path: '/api/jobs/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElevenlabsCallRoute = ApiPublicElevenlabsCallRouteImport.update({
  id: '/api/public/elevenlabs-call',
  path: '/api/public/elevenlabs-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsTranscriptsRoute = ApiReportsTranscriptsRouteImport.update({
  id: '/api/reports/transcripts',
  path: '/api/reports/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsIdRecordingRoute = ApiCallsIdRecordingRouteImport.update({
  id: '/api/calls/$id/recording',
  path: '/api/calls/$id/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsIdStatusRoute = ApiCallsIdStatusRouteImport.update({
  id: '/api/calls/$id/status',
  path: '/api/calls/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsIdTranscriptRoute = ApiCallsIdTranscriptRouteImport.update({
  id: '/api/calls/$id/transcript',
  path: '/api/calls/$id/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidatesIdExportRoute = ApiCandidatesIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiCandidatesIdRoute,
} as any)
const ApiIntegrationsMicrosoftAuthorizeRoute =
  ApiIntegrationsMicrosoftAuthorizeRouteImport.update({
    id: '/api/integrations/microsoft/authorize',
    path: '/api/integrations/microsoft/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMicrosoftCallbackRoute =
  ApiIntegrationsMicrosoftCallbackRouteImport.update({
    id: '/api/integrations/microsoft/callback',
    path: '/api/integrations/microsoft/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsZohoAuthorizeRoute =
  ApiIntegrationsZohoAuthorizeRouteImport.update({
    id: '/api/integrations/zoho/authorize',
    path: '/api/integrations/zoho/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsZohoCallbackRoute =
  ApiIntegrationsZohoCallbackRouteImport.update({
    id: '/api/integrations/zoho/callback',
    path: '/api/integrations/zoho/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCallsWebhookRoute = ApiPublicCallsWebhookRouteImport.update({
  id: '/api/public/calls/webhook',
  path: '/api/public/calls/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/extraction': typeof ExtractionRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRoute
  '/voice': typeof VoiceRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/calls/': typeof CallsIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/api/analytics/calls': typeof ApiAnalyticsCallsRoute
  '/api/analytics/candidates': typeof ApiAnalyticsCandidatesRoute
  '/api/calls/initiate': typeof ApiCallsInitiateRoute
  '/api/calls/webhook': typeof ApiCallsWebhookRoute
  '/api/candidates/$id': typeof ApiCandidatesIdRouteWithChildren
  '/api/candidates/upload': typeof ApiCandidatesUploadRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/interviews/$id': typeof ApiInterviewsIdRoute
  '/api/interviews/availability': typeof ApiInterviewsAvailabilityRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/sync': typeof ApiJobsSyncRoute
  '/api/public/elevenlabs-call': typeof ApiPublicElevenlabsCallRoute
  '/api/reports/transcripts': typeof ApiReportsTranscriptsRoute
  '/api/analytics/': typeof ApiAnalyticsIndexRoute
  '/api/candidates/': typeof ApiCandidatesIndexRoute
  '/api/interviews/': typeof ApiInterviewsIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/calls/$id/recording': typeof ApiCallsIdRecordingRoute
  '/api/calls/$id/status': typeof ApiCallsIdStatusRoute
  '/api/calls/$id/transcript': typeof ApiCallsIdTranscriptRoute
  '/api/candidates/$id/export': typeof ApiCandidatesIdExportRoute
  '/api/integrations/microsoft/authorize': typeof ApiIntegrationsMicrosoftAuthorizeRoute
  '/api/integrations/microsoft/callback': typeof ApiIntegrationsMicrosoftCallbackRoute
  '/api/integrations/zoho/authorize': typeof ApiIntegrationsZohoAuthorizeRoute
  '/api/integrations/zoho/callback': typeof ApiIntegrationsZohoCallbackRoute
  '/api/public/calls/webhook': typeof ApiPublicCallsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/extraction': typeof ExtractionRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRoute
  '/voice': typeof VoiceRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/calls': typeof CallsIndexRoute
  '/candidates': typeof CandidatesIndexRoute
  '/api/analytics/calls': typeof ApiAnalyticsCallsRoute
  '/api/analytics/candidates': typeof ApiAnalyticsCandidatesRoute
  '/api/calls/initiate': typeof ApiCallsInitiateRoute
  '/api/calls/webhook': typeof ApiCallsWebhookRoute
  '/api/candidates/$id': typeof ApiCandidatesIdRouteWithChildren
  '/api/candidates/upload': typeof ApiCandidatesUploadRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/interviews/$id': typeof ApiInterviewsIdRoute
  '/api/interviews/availability': typeof ApiInterviewsAvailabilityRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/sync': typeof ApiJobsSyncRoute
  '/api/public/elevenlabs-call': typeof ApiPublicElevenlabsCallRoute
  '/api/reports/transcripts': typeof ApiReportsTranscriptsRoute
  '/api/analytics': typeof ApiAnalyticsIndexRoute
  '/api/candidates': typeof ApiCandidatesIndexRoute
  '/api/interviews': typeof ApiInterviewsIndexRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/calls/$id/recording': typeof ApiCallsIdRecordingRoute
  '/api/calls/$id/status': typeof ApiCallsIdStatusRoute
  '/api/calls/$id/transcript': typeof ApiCallsIdTranscriptRoute
  '/api/candidates/$id/export': typeof ApiCandidatesIdExportRoute
  '/api/integrations/microsoft/authorize': typeof ApiIntegrationsMicrosoftAuthorizeRoute
  '/api/integrations/microsoft/callback': typeof ApiIntegrationsMicrosoftCallbackRoute
  '/api/integrations/zoho/authorize': typeof ApiIntegrationsZohoAuthorizeRoute
  '/api/integrations/zoho/callback': typeof ApiIntegrationsZohoCallbackRoute
  '/api/public/calls/webhook': typeof ApiPublicCallsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/extraction': typeof ExtractionRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRoute
  '/voice': typeof VoiceRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/calls/': typeof CallsIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/api/analytics/calls': typeof ApiAnalyticsCallsRoute
  '/api/analytics/candidates': typeof ApiAnalyticsCandidatesRoute
  '/api/calls/initiate': typeof ApiCallsInitiateRoute
  '/api/calls/webhook': typeof ApiCallsWebhookRoute
  '/api/candidates/$id': typeof ApiCandidatesIdRouteWithChildren
  '/api/candidates/upload': typeof ApiCandidatesUploadRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/interviews/$id': typeof ApiInterviewsIdRoute
  '/api/interviews/availability': typeof ApiInterviewsAvailabilityRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/sync': typeof ApiJobsSyncRoute
  '/api/public/elevenlabs-call': typeof ApiPublicElevenlabsCallRoute
  '/api/reports/transcripts': typeof ApiReportsTranscriptsRoute
  '/api/analytics/': typeof ApiAnalyticsIndexRoute
  '/api/candidates/': typeof ApiCandidatesIndexRoute
  '/api/interviews/': typeof ApiInterviewsIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/calls/$id/recording': typeof ApiCallsIdRecordingRoute
  '/api/calls/$id/status': typeof ApiCallsIdStatusRoute
  '/api/calls/$id/transcript': typeof ApiCallsIdTranscriptRoute
  '/api/candidates/$id/export': typeof ApiCandidatesIdExportRoute
  '/api/integrations/microsoft/authorize': typeof ApiIntegrationsMicrosoftAuthorizeRoute
  '/api/integrations/microsoft/callback': typeof ApiIntegrationsMicrosoftCallbackRoute
  '/api/integrations/zoho/authorize': typeof ApiIntegrationsZohoAuthorizeRoute
  '/api/integrations/zoho/callback': typeof ApiIntegrationsZohoCallbackRoute
  '/api/public/calls/webhook': typeof ApiPublicCallsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ats'
    | '/audit'
    | '/auth'
    | '/extraction'
    | '/interviews'
    | '/jobs'
    | '/recruiters'
    | '/settings'
    | '/transcripts'
    | '/voice'
    | '/calls/$callId'
    | '/candidates/$candidateId'
    | '/calls/'
    | '/candidates/'
    | '/api/analytics/calls'
    | '/api/analytics/candidates'
    | '/api/calls/initiate'
    | '/api/calls/webhook'
    | '/api/candidates/$id'
    | '/api/candidates/upload'
    | '/api/cron/retention'
    | '/api/interviews/$id'
    | '/api/interviews/availability'
    | '/api/jobs/$id'
    | '/api/jobs/sync'
    | '/api/public/elevenlabs-call'
    | '/api/reports/transcripts'
    | '/api/analytics/'
    | '/api/candidates/'
    | '/api/interviews/'
    | '/api/jobs/'
    | '/api/calls/$id/recording'
    | '/api/calls/$id/status'
    | '/api/calls/$id/transcript'
    | '/api/candidates/$id/export'
    | '/api/integrations/microsoft/authorize'
    | '/api/integrations/microsoft/callback'
    | '/api/integrations/zoho/authorize'
    | '/api/integrations/zoho/callback'
    | '/api/public/calls/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ats'
    | '/audit'
    | '/auth'
    | '/extraction'
    | '/interviews'
    | '/jobs'
    | '/recruiters'
    | '/settings'
    | '/transcripts'
    | '/voice'
    | '/calls/$callId'
    | '/candidates/$candidateId'
    | '/calls'
    | '/candidates'
    | '/api/analytics/calls'
    | '/api/analytics/candidates'
    | '/api/calls/initiate'
    | '/api/calls/webhook'
    | '/api/candidates/$id'
    | '/api/candidates/upload'
    | '/api/cron/retention'
    | '/api/interviews/$id'
    | '/api/interviews/availability'
    | '/api/jobs/$id'
    | '/api/jobs/sync'
    | '/api/public/elevenlabs-call'
    | '/api/reports/transcripts'
    | '/api/analytics'
    | '/api/candidates'
    | '/api/interviews'
    | '/api/jobs'
    | '/api/calls/$id/recording'
    | '/api/calls/$id/status'
    | '/api/calls/$id/transcript'
    | '/api/candidates/$id/export'
    | '/api/integrations/microsoft/authorize'
    | '/api/integrations/microsoft/callback'
    | '/api/integrations/zoho/authorize'
    | '/api/integrations/zoho/callback'
    | '/api/public/calls/webhook'
  id:
    | '__root__'
    | '/'
    | '/ats'
    | '/audit'
    | '/auth'
    | '/extraction'
    | '/interviews'
    | '/jobs'
    | '/recruiters'
    | '/settings'
    | '/transcripts'
    | '/voice'
    | '/calls/$callId'
    | '/candidates/$candidateId'
    | '/calls/'
    | '/candidates/'
    | '/api/analytics/calls'
    | '/api/analytics/candidates'
    | '/api/calls/initiate'
    | '/api/calls/webhook'
    | '/api/candidates/$id'
    | '/api/candidates/upload'
    | '/api/cron/retention'
    | '/api/interviews/$id'
    | '/api/interviews/availability'
    | '/api/jobs/$id'
    | '/api/jobs/sync'
    | '/api/public/elevenlabs-call'
    | '/api/reports/transcripts'
    | '/api/analytics/'
    | '/api/candidates/'
    | '/api/interviews/'
    | '/api/jobs/'
    | '/api/calls/$id/recording'
    | '/api/calls/$id/status'
    | '/api/calls/$id/transcript'
    | '/api/candidates/$id/export'
    | '/api/integrations/microsoft/authorize'
    | '/api/integrations/microsoft/callback'
    | '/api/integrations/zoho/authorize'
    | '/api/integrations/zoho/callback'
    | '/api/public/calls/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtsRoute: typeof AtsRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  ExtractionRoute: typeof ExtractionRoute
  InterviewsRoute: typeof InterviewsRoute
  JobsRoute: typeof JobsRoute
  RecruitersRoute: typeof RecruitersRoute
  SettingsRoute: typeof SettingsRoute
  TranscriptsRoute: typeof TranscriptsRoute
  VoiceRoute: typeof VoiceRoute
  CallsCallIdRoute: typeof CallsCallIdRoute
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRoute
  CallsIndexRoute: typeof CallsIndexRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  ApiAnalyticsCallsRoute: typeof ApiAnalyticsCallsRoute
  ApiAnalyticsCandidatesRoute: typeof ApiAnalyticsCandidatesRoute
  ApiCallsInitiateRoute: typeof ApiCallsInitiateRoute
  ApiCallsWebhookRoute: typeof ApiCallsWebhookRoute
  ApiCandidatesIdRoute: typeof ApiCandidatesIdRouteWithChildren
  ApiCandidatesUploadRoute: typeof ApiCandidatesUploadRoute
  ApiCronRetentionRoute: typeof ApiCronRetentionRoute
  ApiInterviewsIdRoute: typeof ApiInterviewsIdRoute
  ApiInterviewsAvailabilityRoute: typeof ApiInterviewsAvailabilityRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiJobsSyncRoute: typeof ApiJobsSyncRoute
  ApiPublicElevenlabsCallRoute: typeof ApiPublicElevenlabsCallRoute
  ApiReportsTranscriptsRoute: typeof ApiReportsTranscriptsRoute
  ApiAnalyticsIndexRoute: typeof ApiAnalyticsIndexRoute
  ApiCandidatesIndexRoute: typeof ApiCandidatesIndexRoute
  ApiInterviewsIndexRoute: typeof ApiInterviewsIndexRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiCallsIdRecordingRoute: typeof ApiCallsIdRecordingRoute
  ApiCallsIdStatusRoute: typeof ApiCallsIdStatusRoute
  ApiCallsIdTranscriptRoute: typeof ApiCallsIdTranscriptRoute
  ApiIntegrationsMicrosoftAuthorizeRoute: typeof ApiIntegrationsMicrosoftAuthorizeRoute
  ApiIntegrationsMicrosoftCallbackRoute: typeof ApiIntegrationsMicrosoftCallbackRoute
  ApiIntegrationsZohoAuthorizeRoute: typeof ApiIntegrationsZohoAuthorizeRoute
  ApiIntegrationsZohoCallbackRoute: typeof ApiIntegrationsZohoCallbackRoute
  ApiPublicCallsWebhookRoute: typeof ApiPublicCallsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extraction': {
      id: '/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof ExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$callId': {
      id: '/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/calls/$callId'
      preLoaderRoute: typeof CallsCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$candidateId': {
      id: '/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/': {
      id: '/api/analytics/'
      path: '/api/analytics'
      fullPath: '/api/analytics/'
      preLoaderRoute: typeof ApiAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/calls': {
      id: '/api/analytics/calls'
      path: '/api/analytics/calls'
      fullPath: '/api/analytics/calls'
      preLoaderRoute: typeof ApiAnalyticsCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/candidates': {
      id: '/api/analytics/candidates'
      path: '/api/analytics/candidates'
      fullPath: '/api/analytics/candidates'
      preLoaderRoute: typeof ApiAnalyticsCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/initiate': {
      id: '/api/calls/initiate'
      path: '/api/calls/initiate'
      fullPath: '/api/calls/initiate'
      preLoaderRoute: typeof ApiCallsInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/webhook': {
      id: '/api/calls/webhook'
      path: '/api/calls/webhook'
      fullPath: '/api/calls/webhook'
      preLoaderRoute: typeof ApiCallsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidates/': {
      id: '/api/candidates/'
      path: '/api/candidates'
      fullPath: '/api/candidates/'
      preLoaderRoute: typeof ApiCandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidates/$id': {
      id: '/api/candidates/$id'
      path: '/api/candidates/$id'
      fullPath: '/api/candidates/$id'
      preLoaderRoute: typeof ApiCandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidates/upload': {
      id: '/api/candidates/upload'
      path: '/api/candidates/upload'
      fullPath: '/api/candidates/upload'
      preLoaderRoute: typeof ApiCandidatesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/retention': {
      id: '/api/cron/retention'
      path: '/api/cron/retention'
      fullPath: '/api/cron/retention'
      preLoaderRoute: typeof ApiCronRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interviews/': {
      id: '/api/interviews/'
      path: '/api/interviews'
      fullPath: '/api/interviews/'
      preLoaderRoute: typeof ApiInterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interviews/$id': {
      id: '/api/interviews/$id'
      path: '/api/interviews/$id'
      fullPath: '/api/interviews/$id'
      preLoaderRoute: typeof ApiInterviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interviews/availability': {
      id: '/api/interviews/availability'
      path: '/api/interviews/availability'
      fullPath: '/api/interviews/availability'
      preLoaderRoute: typeof ApiInterviewsAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/sync': {
      id: '/api/jobs/sync'
      path: '/api/jobs/sync'
      fullPath: '/api/jobs/sync'
      preLoaderRoute: typeof ApiJobsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs-call': {
      id: '/api/public/elevenlabs-call'
      path: '/api/public/elevenlabs-call'
      fullPath: '/api/public/elevenlabs-call'
      preLoaderRoute: typeof ApiPublicElevenlabsCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/transcripts': {
      id: '/api/reports/transcripts'
      path: '/api/reports/transcripts'
      fullPath: '/api/reports/transcripts'
      preLoaderRoute: typeof ApiReportsTranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/$id/recording': {
      id: '/api/calls/$id/recording'
      path: '/api/calls/$id/recording'
      fullPath: '/api/calls/$id/recording'
      preLoaderRoute: typeof ApiCallsIdRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/$id/status': {
      id: '/api/calls/$id/status'
      path: '/api/calls/$id/status'
      fullPath: '/api/calls/$id/status'
      preLoaderRoute: typeof ApiCallsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/$id/transcript': {
      id: '/api/calls/$id/transcript'
      path: '/api/calls/$id/transcript'
      fullPath: '/api/calls/$id/transcript'
      preLoaderRoute: typeof ApiCallsIdTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidates/$id/export': {
      id: '/api/candidates/$id/export'
      path: '/export'
      fullPath: '/api/candidates/$id/export'
      preLoaderRoute: typeof ApiCandidatesIdExportRouteImport
      parentRoute: typeof ApiCandidatesIdRoute
    }
    '/api/integrations/microsoft/authorize': {
      id: '/api/integrations/microsoft/authorize'
      path: '/api/integrations/microsoft/authorize'
      fullPath: '/api/integrations/microsoft/authorize'
      preLoaderRoute: typeof ApiIntegrationsMicrosoftAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/microsoft/callback': {
      id: '/api/integrations/microsoft/callback'
      path: '/api/integrations/microsoft/callback'
      fullPath: '/api/integrations/microsoft/callback'
      preLoaderRoute: typeof ApiIntegrationsMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/zoho/authorize': {
      id: '/api/integrations/zoho/authorize'
      path: '/api/integrations/zoho/authorize'
      fullPath: '/api/integrations/zoho/authorize'
      preLoaderRoute: typeof ApiIntegrationsZohoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/zoho/callback': {
      id: '/api/integrations/zoho/callback'
      path: '/api/integrations/zoho/callback'
      fullPath: '/api/integrations/zoho/callback'
      preLoaderRoute: typeof ApiIntegrationsZohoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calls/webhook': {
      id: '/api/public/calls/webhook'
      path: '/api/public/calls/webhook'
      fullPath: '/api/public/calls/webhook'
      preLoaderRoute: typeof ApiPublicCallsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiCandidatesIdRouteChildren {
  ApiCandidatesIdExportRoute: typeof ApiCandidatesIdExportRoute
}

const ApiCandidatesIdRouteChildren: ApiCandidatesIdRouteChildren = {
  ApiCandidatesIdExportRoute: ApiCandidatesIdExportRoute,
}

const ApiCandidatesIdRouteWithChildren = ApiCandidatesIdRoute._addFileChildren(
  ApiCandidatesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsRoute: AtsRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  ExtractionRoute: ExtractionRoute,
  InterviewsRoute: InterviewsRoute,
  JobsRoute: JobsRoute,
  RecruitersRoute: RecruitersRoute,
  SettingsRoute: SettingsRoute,
  TranscriptsRoute: TranscriptsRoute,
  VoiceRoute: VoiceRoute,
  CallsCallIdRoute: CallsCallIdRoute,
  CandidatesCandidateIdRoute: CandidatesCandidateIdRoute,
  CallsIndexRoute: CallsIndexRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  ApiAnalyticsCallsRoute: ApiAnalyticsCallsRoute,
  ApiAnalyticsCandidatesRoute: ApiAnalyticsCandidatesRoute,
  ApiCallsInitiateRoute: ApiCallsInitiateRoute,
  ApiCallsWebhookRoute: ApiCallsWebhookRoute,
  ApiCandidatesIdRoute: ApiCandidatesIdRouteWithChildren,
  ApiCandidatesUploadRoute: ApiCandidatesUploadRoute,
  ApiCronRetentionRoute: ApiCronRetentionRoute,
  ApiInterviewsIdRoute: ApiInterviewsIdRoute,
  ApiInterviewsAvailabilityRoute: ApiInterviewsAvailabilityRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiJobsSyncRoute: ApiJobsSyncRoute,
  ApiPublicElevenlabsCallRoute: ApiPublicElevenlabsCallRoute,
  ApiReportsTranscriptsRoute: ApiReportsTranscriptsRoute,
  ApiAnalyticsIndexRoute: ApiAnalyticsIndexRoute,
  ApiCandidatesIndexRoute: ApiCandidatesIndexRoute,
  ApiInterviewsIndexRoute: ApiInterviewsIndexRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiCallsIdRecordingRoute: ApiCallsIdRecordingRoute,
  ApiCallsIdStatusRoute: ApiCallsIdStatusRoute,
  ApiCallsIdTranscriptRoute: ApiCallsIdTranscriptRoute,
  ApiIntegrationsMicrosoftAuthorizeRoute:
    ApiIntegrationsMicrosoftAuthorizeRoute,
  ApiIntegrationsMicrosoftCallbackRoute: ApiIntegrationsMicrosoftCallbackRoute,
  ApiIntegrationsZohoAuthorizeRoute: ApiIntegrationsZohoAuthorizeRoute,
  ApiIntegrationsZohoCallbackRoute: ApiIntegrationsZohoCallbackRoute,
  ApiPublicCallsWebhookRoute: ApiPublicCallsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
